package com.cebi.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Ccdp010Id generated by hbm2java
 */
@Embeddable
public class BranchRep implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String brcdBankCd;
	private String reportDate;
	private String branchCode;
	private String acctNo;

	public BranchRep() {
	}

	public BranchRep(String brcdBankCd, String reportDate, String branchCode, String acctNo) {
		this.brcdBankCd = brcdBankCd;
		this.reportDate = reportDate;
		this.branchCode = branchCode;
		this.acctNo = acctNo;
	}

	@Column(name = "BRCD_BANK_CD", nullable = false, length = 5)
	public String getBrcdBankCd() {
		return this.brcdBankCd;
	}

	public void setBrcdBankCd(String brcdBankCd) {
		this.brcdBankCd = brcdBankCd;
	}

	@Column(name = "REPORT_DATE", nullable = false, length = 10)
	public String getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(String reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "BRANCH_CODE", nullable = false, length = 5)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "ACCT_NO", nullable = false, length = 17)
	public String getAcctNo() {
		return this.acctNo;
	}

	public void setAcctNo(String acctNo) {
		this.acctNo = acctNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BranchRep))
			return false;
		BranchRep castOther = (BranchRep) other;

		return ((this.getBrcdBankCd() == castOther.getBrcdBankCd()) || (this.getBrcdBankCd() != null && castOther.getBrcdBankCd() != null && this.getBrcdBankCd().equals(castOther.getBrcdBankCd()))) && ((this.getReportDate() == castOther.getReportDate()) || (this.getReportDate() != null && castOther.getReportDate() != null && this.getReportDate().equals(castOther.getReportDate()))) && ((this.getBranchCode() == castOther.getBranchCode()) || (this.getBranchCode() != null && castOther.getBranchCode() != null && this.getBranchCode().equals(castOther.getBranchCode()))) && ((this.getAcctNo() == castOther.getAcctNo()) || (this.getAcctNo() != null && castOther.getAcctNo() != null && this.getAcctNo().equals(castOther.getAcctNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBrcdBankCd() == null ? 0 : this.getBrcdBankCd().hashCode());
		result = 37 * result + (getReportDate() == null ? 0 : this.getReportDate().hashCode());
		result = 37 * result + (getBranchCode() == null ? 0 : this.getBranchCode().hashCode());
		result = 37 * result + (getAcctNo() == null ? 0 : this.getAcctNo().hashCode());
		return result;
	}

}