package com.cebi.entity;


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * BranchInformation generated by hbm2java
 */
@Entity
@Table(name = "branch_information")
public class BranchInformation implements java.io.Serializable {

	private static final long serialVersionUID = 669516686265418310L;
	private BranchInformationId id;
	private String brcdBranchName;
	private String brcdAddr1;
	private String brcdAddr2;
	private String brcdAddr3;
	private String brcdCity;
	private Integer brcdPin;
	private String brcdMkrCode;
	private Date brcdMkrDate;
	private String brcdMkrTime;
	private String brcdChkrCode;
	private Date brcdChkrDate;
	private String brcdChkrTime;
	private Byte brcdStatus;
	private String brcdRegionalId;
	private String brcdZonalId;
	private String brcdCircleId;
	private transient boolean consolidated=false;


	public BranchInformation() {
	}

	public BranchInformation(BranchInformationId id, String brcdBranchName) {
		this.id = id;
		this.brcdBranchName = brcdBranchName;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "brcdBankCd", column = @Column(name = "BRCD_BANK_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "brcdBranchCd", column = @Column(name = "BRCD_BRANCH_CD", nullable = false, length = 5)) })
	public BranchInformationId getId() {
		return this.id;
	}

	public void setId(BranchInformationId id) {
		this.id = id;
	}

	@Column(name = "BRCD_BRANCH_NAME", nullable = false, length = 40)
	public String getBrcdBranchName() {
		return this.brcdBranchName;
	}

	public void setBrcdBranchName(String brcdBranchName) {
		this.brcdBranchName = brcdBranchName;
	}

	@Column(name = "BRCD_ADDR_1", length = 30)
	public String getBrcdAddr1() {
		return this.brcdAddr1;
	}

	public void setBrcdAddr1(String brcdAddr1) {
		this.brcdAddr1 = brcdAddr1;
	}

	@Column(name = "BRCD_ADDR_2", length = 30)
	public String getBrcdAddr2() {
		return this.brcdAddr2;
	}

	public void setBrcdAddr2(String brcdAddr2) {
		this.brcdAddr2 = brcdAddr2;
	}

	@Column(name = "BRCD_ADDR_3", length = 30)
	public String getBrcdAddr3() {
		return this.brcdAddr3;
	}

	public void setBrcdAddr3(String brcdAddr3) {
		this.brcdAddr3 = brcdAddr3;
	}

	@Column(name = "BRCD_CITY", length = 20)
	public String getBrcdCity() {
		return this.brcdCity;
	}

	public void setBrcdCity(String brcdCity) {
		this.brcdCity = brcdCity;
	}

	@Column(name = "BRCD_PIN")
	public Integer getBrcdPin() {
		return this.brcdPin;
	}

	public void setBrcdPin(Integer brcdPin) {
		this.brcdPin = brcdPin;
	}

	@Column(name = "BRCD_MKR_CODE", length = 20)
	public String getBrcdMkrCode() {
		return this.brcdMkrCode;
	}

	public void setBrcdMkrCode(String brcdMkrCode) {
		this.brcdMkrCode = brcdMkrCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BRCD_MKR_DATE", length = 19)
	public Date getBrcdMkrDate() {
		return this.brcdMkrDate;
	}

	public void setBrcdMkrDate(Date brcdMkrDate) {
		this.brcdMkrDate = brcdMkrDate;
	}

	@Column(name = "BRCD_MKR_TIME", length = 15)
	public String getBrcdMkrTime() {
		return this.brcdMkrTime;
	}

	public void setBrcdMkrTime(String brcdMkrTime) {
		this.brcdMkrTime = brcdMkrTime;
	}

	@Column(name = "BRCD_CHKR_CODE", length = 20)
	public String getBrcdChkrCode() {
		return this.brcdChkrCode;
	}

	public void setBrcdChkrCode(String brcdChkrCode) {
		this.brcdChkrCode = brcdChkrCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BRCD_CHKR_DATE", length = 19)
	public Date getBrcdChkrDate() {
		return this.brcdChkrDate;
	}

	public void setBrcdChkrDate(Date brcdChkrDate) {
		this.brcdChkrDate = brcdChkrDate;
	}

	@Column(name = "BRCD_CHKR_TIME", length = 15)
	public String getBrcdChkrTime() {
		return this.brcdChkrTime;
	}

	public void setBrcdChkrTime(String brcdChkrTime) {
		this.brcdChkrTime = brcdChkrTime;
	}

	@Column(name = "BRCD_STATUS")
	public Byte getBrcdStatus() {
		return this.brcdStatus;
	}

	public void setBrcdStatus(Byte brcdStatus) {
		this.brcdStatus = brcdStatus;
	}

	@Column(name = "BRCD_REGIONAL_ID", length = 30)
	public String getBrcdRegionalId() {
		return this.brcdRegionalId;
	}

	public void setBrcdRegionalId(String brcdRegionalId) {
		this.brcdRegionalId = brcdRegionalId;
	}

	@Column(name = "BRCD_ZONAL_ID", length = 30)
	public String getBrcdZonalId() {
		return this.brcdZonalId;
	}

	public void setBrcdZonalId(String brcdZonalId) {
		this.brcdZonalId = brcdZonalId;
	}

	@Column(name = "BRCD_CIRCLE_ID", length = 30)
	public String getBrcdCircleId() {
		return this.brcdCircleId;
	}

	public void setBrcdCircleId(String brcdCircleId) {
		this.brcdCircleId = brcdCircleId;
	}
	@Transient
	public boolean isConsolidated() {
		return consolidated;
	}

	public void setConsolidated(boolean consolidated) {
		this.consolidated = consolidated;
	}
}
