package com.cebi.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BranchInformationId generated by hbm2java
 */
@Embeddable
public class BranchInformationId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3284115083130295594L;
	private String brcdBankCd;
	private String brcdBranchCd;

	public BranchInformationId() {
	}

	public BranchInformationId(String brcdBankCd, String brcdBranchCd) {
		this.brcdBankCd = brcdBankCd;
		this.brcdBranchCd = brcdBranchCd;
	}

	@Column(name = "BRCD_BANK_CD", nullable = false, length = 3)
	public String getBrcdBankCd() {
		return this.brcdBankCd;
	}

	public void setBrcdBankCd(String brcdBankCd) {
		this.brcdBankCd = brcdBankCd;
	}

	@Column(name = "BRCD_BRANCH_CD", nullable = false, length = 5)
	public String getBrcdBranchCd() {
		return this.brcdBranchCd;
	}

	public void setBrcdBranchCd(String brcdBranchCd) {
		this.brcdBranchCd = brcdBranchCd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BranchInformationId))
			return false;
		BranchInformationId castOther = (BranchInformationId) other;

		return ((this.getBrcdBankCd() == castOther.getBrcdBankCd()) || (this.getBrcdBankCd() != null && castOther.getBrcdBankCd() != null && this.getBrcdBankCd().equals(castOther.getBrcdBankCd()))) && ((this.getBrcdBranchCd() == castOther.getBrcdBranchCd()) || (this.getBrcdBranchCd() != null && castOther.getBrcdBranchCd() != null && this.getBrcdBranchCd().equals(castOther.getBrcdBranchCd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBrcdBankCd() == null ? 0 : this.getBrcdBankCd().hashCode());
		result = 37 * result + (getBrcdBranchCd() == null ? 0 : this.getBrcdBranchCd().hashCode());
		return result;
	}

}
