package com.cebi.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ccdp010 generated by hbm2java
 */
@Entity
@Table(name = "ccdp010")
public class Ccdp010 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BranchRep id;
	private String module;
	private String circle;
	private String region;
	private String branchName;
	private String segment;
	private String cifNo;
	private String sector;
	private String facilityType;
	private String borrName;
	private String limitAmt;
	private String dp;
	private String irregularAmt;
	private String natOfBills;
	private String securityAmt;
	private String chargesCreated;
	private String primaryTang;
	private String collateralTang;
	private String totalTang;
	private String constituent;
	private String allocated;
	private String inttRate;
	private String crSumm;
	private String irregularDate;
	private String lastCrDate;
	private String crr;
	private String insuDate;
	private String insuAmt;
	private String receEcgc;
	private String sancDate;
	private String stockStmntDate;
	private String totOs;
	private String secuTangAsset;
	private String bankSecu;
	private String secureEcgc;
	private String unsecured;
	private String assetSubclass;
	private String pbRd;
	private String unrealisedIntt;
	private String npaDate;
	private String inca;
	private String provAmt;
	private String provUnsec;
	private String inttSusp;
	private String adjUnsecuPortion;
	private String secuPortion;
	private String rstrctrProv;
	private String rstrctrDate;
	private String oneNpa;
	/*private String REC_STATUS="";*/
	public Ccdp010() {
	}

	public Ccdp010(BranchRep id) {
		this.id = id;
	}

	public Ccdp010(BranchRep id, String module, String circle, String region,
			String branchName, String segment, String cifNo, String sector,
			String facilityType, String borrName, String limitAmt, String dp,
			String irregularAmt, String natOfBills, String securityAmt,
			String chargesCreated, String primaryTang, String collateralTang,
			String totalTang, String constituent, String allocated,
			String inttRate, String crSumm, String irregularDate,
			String lastCrDate, String crr, String insuDate, String insuAmt,
			String receEcgc, String sancDate, String stockStmntDate,
			String totOs, String secuTangAsset, String bankSecu,
			String secureEcgc, String unsecured, String assetSubclass,
			String pbRd, String unrealisedIntt, String npaDate, String inca,
			String provAmt, String provUnsec, String inttSusp,
			String adjUnsecuPortion, String secuPortion, String rstrctrProv,
			String rstrctrDate, String oneNpa/*,String REC_STATUS*/) {
		this.id = id;
		/*this.REC_STATUS=REC_STATUS;*/
		this.module = module;
		this.circle = circle;
		this.region = region;
		this.branchName = branchName;
		this.segment = segment;
		this.cifNo = cifNo;
		this.sector = sector;
		this.facilityType = facilityType;
		this.borrName = borrName;
		this.limitAmt = limitAmt;
		this.dp = dp;
		this.irregularAmt = irregularAmt;
		this.natOfBills = natOfBills;
		this.securityAmt = securityAmt;
		this.chargesCreated = chargesCreated;
		this.primaryTang = primaryTang;
		this.collateralTang = collateralTang;
		this.totalTang = totalTang;
		this.constituent = constituent;
		this.allocated = allocated;
		this.inttRate = inttRate;
		this.crSumm = crSumm;
		this.irregularDate = irregularDate;
		this.lastCrDate = lastCrDate;
		this.crr = crr;
		this.insuDate = insuDate;
		this.insuAmt = insuAmt;
		this.receEcgc = receEcgc;
		this.sancDate = sancDate;
		this.stockStmntDate = stockStmntDate;
		this.totOs = totOs;
		this.secuTangAsset = secuTangAsset;
		this.bankSecu = bankSecu;
		this.secureEcgc = secureEcgc;
		this.unsecured = unsecured;
		this.assetSubclass = assetSubclass;
		this.pbRd = pbRd;
		this.unrealisedIntt = unrealisedIntt;
		this.npaDate = npaDate;
		this.inca = inca;
		this.provAmt = provAmt;
		this.provUnsec = provUnsec;
		this.inttSusp = inttSusp;
		this.adjUnsecuPortion = adjUnsecuPortion;
		this.secuPortion = secuPortion;
		this.rstrctrProv = rstrctrProv;
		this.rstrctrDate = rstrctrDate;
		this.oneNpa = oneNpa;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "brcdBankCd", column = @Column(name = "BRCD_BANK_CD", nullable = false, length = 5)),
			@AttributeOverride(name = "reportDate", column = @Column(name = "REPORT_DATE", nullable = false, length = 10)),
			@AttributeOverride(name = "branchCode", column = @Column(name = "BRANCH_CODE", nullable = false, length = 5)),
			@AttributeOverride(name = "acctNo", column = @Column(name = "ACCT_NO", nullable = false, length = 17)) })
	public BranchRep getId() {
		return this.id;
	}

	public void setId(BranchRep id) {
		this.id = id;
	}

	@Column(name = "MODULE", length = 10)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "CIRCLE", length = 9)
	public String getCircle() {
		return this.circle;
	}

	public void setCircle(String circle) {
		this.circle = circle;
	}

	@Column(name = "REGION", length = 3)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "BRANCH_NAME", length = 30)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "SEGMENT", length = 5)
	public String getSegment() {
		return this.segment;
	}

	public void setSegment(String segment) {
		this.segment = segment;
	}

	@Column(name = "CIF_NO", length = 16)
	public String getCifNo() {
		return this.cifNo;
	}

	public void setCifNo(String cifNo) {
		this.cifNo = cifNo;
	}

	@Column(name = "SECTOR", length = 10)
	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	@Column(name = "FACILITY_TYPE", length = 5)
	public String getFacilityType() {
		return this.facilityType;
	}

	public void setFacilityType(String facilityType) {
		this.facilityType = facilityType;
	}

	@Column(name = "BORR_NAME", length = 30)
	public String getBorrName() {
		return this.borrName;
	}

	public void setBorrName(String borrName) {
		this.borrName = borrName;
	}

	@Column(name = "LIMIT_AMT", length = 17)
	public String getLimitAmt() {
		return this.limitAmt;
	}

	public void setLimitAmt(String limitAmt) {
		this.limitAmt = limitAmt;
	}

	@Column(name = "DP", length = 17)
	public String getDp() {
		return this.dp;
	}

	public void setDp(String dp) {
		this.dp = dp;
	}

	@Column(name = "IRREGULAR_AMT", length = 17)
	public String getIrregularAmt() {
		return this.irregularAmt;
	}

	public void setIrregularAmt(String irregularAmt) {
		this.irregularAmt = irregularAmt;
	}

	@Column(name = "NAT_OF_BILLS", length = 10)
	public String getNatOfBills() {
		return this.natOfBills;
	}

	public void setNatOfBills(String natOfBills) {
		this.natOfBills = natOfBills;
	}

	@Column(name = "SECURITY_AMT", length = 15)
	public String getSecurityAmt() {
		return this.securityAmt;
	}

	public void setSecurityAmt(String securityAmt) {
		this.securityAmt = securityAmt;
	}

	@Column(name = "CHARGES_CREATED", length = 15)
	public String getChargesCreated() {
		return this.chargesCreated;
	}

	public void setChargesCreated(String chargesCreated) {
		this.chargesCreated = chargesCreated;
	}

	@Column(name = "PRIMARY_TANG", length = 17)
	public String getPrimaryTang() {
		return this.primaryTang;
	}

	public void setPrimaryTang(String primaryTang) {
		this.primaryTang = primaryTang;
	}

	@Column(name = "COLLATERAL_TANG", length = 17)
	public String getCollateralTang() {
		return this.collateralTang;
	}

	public void setCollateralTang(String collateralTang) {
		this.collateralTang = collateralTang;
	}

	@Column(name = "TOTAL_TANG", length = 17)
	public String getTotalTang() {
		return this.totalTang;
	}

	public void setTotalTang(String totalTang) {
		this.totalTang = totalTang;
	}

	@Column(name = "CONSTITUENT", length = 12)
	public String getConstituent() {
		return this.constituent;
	}

	public void setConstituent(String constituent) {
		this.constituent = constituent;
	}

	@Column(name = "ALLOCATED", length = 1)
	public String getAllocated() {
		return this.allocated;
	}

	public void setAllocated(String allocated) {
		this.allocated = allocated;
	}

	@Column(name = "INTT_RATE", length = 4)
	public String getInttRate() {
		return this.inttRate;
	}

	public void setInttRate(String inttRate) {
		this.inttRate = inttRate;
	}

	@Column(name = "CR_SUMM", length = 12)
	public String getCrSumm() {
		return this.crSumm;
	}

	public void setCrSumm(String crSumm) {
		this.crSumm = crSumm;
	}

	@Column(name = "IRREGULAR_DATE", length = 10)
	public String getIrregularDate() {
		return this.irregularDate;
	}

	public void setIrregularDate(String irregularDate) {
		this.irregularDate = irregularDate;
	}

	@Column(name = "LAST_CR_DATE", length = 10)
	public String getLastCrDate() {
		return this.lastCrDate;
	}

	public void setLastCrDate(String lastCrDate) {
		this.lastCrDate = lastCrDate;
	}

	@Column(name = "CRR", length = 5)
	public String getCrr() {
		return this.crr;
	}

	public void setCrr(String crr) {
		this.crr = crr;
	}

	@Column(name = "INSU_DATE", length = 10)
	public String getInsuDate() {
		return this.insuDate;
	}

	public void setInsuDate(String insuDate) {
		this.insuDate = insuDate;
	}

	@Column(name = "INSU_AMT", length = 17)
	public String getInsuAmt() {
		return this.insuAmt;
	}

	public void setInsuAmt(String insuAmt) {
		this.insuAmt = insuAmt;
	}

	@Column(name = "RECE_ECGC", length = 17)
	public String getReceEcgc() {
		return this.receEcgc;
	}

	public void setReceEcgc(String receEcgc) {
		this.receEcgc = receEcgc;
	}

	@Column(name = "SANC_DATE", length = 10)
	public String getSancDate() {
		return this.sancDate;
	}

	public void setSancDate(String sancDate) {
		this.sancDate = sancDate;
	}

	@Column(name = "STOCK_STMNT_DATE", length = 10)
	public String getStockStmntDate() {
		return this.stockStmntDate;
	}

	public void setStockStmntDate(String stockStmntDate) {
		this.stockStmntDate = stockStmntDate;
	}

	@Column(name = "TOT_OS", length = 17)
	public String getTotOs() {
		return this.totOs;
	}

	public void setTotOs(String totOs) {
		this.totOs = totOs;
	}

	@Column(name = "SECU_TANG_ASSET", length = 17)
	public String getSecuTangAsset() {
		return this.secuTangAsset;
	}

	public void setSecuTangAsset(String secuTangAsset) {
		this.secuTangAsset = secuTangAsset;
	}

	@Column(name = "BANK_SECU", length = 17)
	public String getBankSecu() {
		return this.bankSecu;
	}

	public void setBankSecu(String bankSecu) {
		this.bankSecu = bankSecu;
	}

	@Column(name = "SECURE_ECGC", length = 17)
	public String getSecureEcgc() {
		return this.secureEcgc;
	}

	public void setSecureEcgc(String secureEcgc) {
		this.secureEcgc = secureEcgc;
	}

	@Column(name = "UNSECURED", length = 17)
	public String getUnsecured() {
		return this.unsecured;
	}

	public void setUnsecured(String unsecured) {
		this.unsecured = unsecured;
	}

	@Column(name = "ASSET_SUBCLASS", length = 2)
	public String getAssetSubclass() {
		return this.assetSubclass;
	}

	public void setAssetSubclass(String assetSubclass) {
		this.assetSubclass = assetSubclass;
	}

	@Column(name = "PB_RD", length = 2)
	public String getPbRd() {
		return this.pbRd;
	}

	public void setPbRd(String pbRd) {
		this.pbRd = pbRd;
	}

	@Column(name = "UNREALISED_INTT", length = 17)
	public String getUnrealisedIntt() {
		return this.unrealisedIntt;
	}

	public void setUnrealisedIntt(String unrealisedIntt) {
		this.unrealisedIntt = unrealisedIntt;
	}

	@Column(name = "NPA_DATE", length = 10)
	public String getNpaDate() {
		return this.npaDate;
	}

	public void setNpaDate(String npaDate) {
		this.npaDate = npaDate;
	}

	@Column(name = "INCA", length = 17)
	public String getInca() {
		return this.inca;
	}

	public void setInca(String inca) {
		this.inca = inca;
	}

	@Column(name = "PROV_AMT", length = 17)
	public String getProvAmt() {
		return this.provAmt;
	}

	public void setProvAmt(String provAmt) {
		this.provAmt = provAmt;
	}

	@Column(name = "PROV_UNSEC", length = 17)
	public String getProvUnsec() {
		return this.provUnsec;
	}

	public void setProvUnsec(String provUnsec) {
		this.provUnsec = provUnsec;
	}

	@Column(name = "INTT_SUSP", length = 17)
	public String getInttSusp() {
		return this.inttSusp;
	}

	public void setInttSusp(String inttSusp) {
		this.inttSusp = inttSusp;
	}

	@Column(name = "ADJ_UNSECU_PORTION", length = 17)
	public String getAdjUnsecuPortion() {
		return this.adjUnsecuPortion;
	}

	public void setAdjUnsecuPortion(String adjUnsecuPortion) {
		this.adjUnsecuPortion = adjUnsecuPortion;
	}

	@Column(name = "SECU_PORTION", length = 17)
	public String getSecuPortion() {
		return this.secuPortion;
	}

	public void setSecuPortion(String secuPortion) {
		this.secuPortion = secuPortion;
	}

	@Column(name = "RSTRCTR_PROV", length = 17)
	public String getRstrctrProv() {
		return this.rstrctrProv;
	}

	public void setRstrctrProv(String rstrctrProv) {
		this.rstrctrProv = rstrctrProv;
	}

	@Column(name = "RSTRCTR_DATE", length = 10)
	public String getRstrctrDate() {
		return this.rstrctrDate;
	}

	public void setRstrctrDate(String rstrctrDate) {
		this.rstrctrDate = rstrctrDate;
	}

	@Column(name = "ONE_NPA", length = 1)
	public String getOneNpa() {
		return this.oneNpa;
	}

	public void setOneNpa(String oneNpa) {
		this.oneNpa = oneNpa;
	}

/*	public String getREC_STATUS() {
		return REC_STATUS;
	}

	public void setREC_STATUS(String rEC_STATUS) {
		REC_STATUS = rEC_STATUS;
	}*/


}
